# Numpy For Machine Learning

Numpy computations are about 5 to 100 times faster than similar calculations. Because they are implemented in C. For this reason, scipy, pandas, matplotlib and scikit-learn are all built on top of it. Thus knowing Numpy is a neccessity.

In this lesson we will be learning just about enogh numpy to get you started on your study of machine learning or if you want to brush up your knowledge of Numpy.

Python is loosely typed, which means you can always reassign a different type to a variable other than what it was initialy declared with.

For example:

In [ ]:
first = 1
first = "1"
first = True

In C, C++, Java or other compiled languages this will fail.

This characteristic of python is one of the reasons why Python is easier to learn and also the reason why its slower than compiled languages.

Numpy is coded in C. Even though you are not require to declare types, it does type conversion under the hood, converting all elements of your array to the same type.

Lets start off by creating our first array in Numpy.

In [3]:
# Default python array
scores = [1, 2, 3, 4]
print(scores)

[1, 2, 3, 4]


In [4]:
# Numpy array
import numpy as np


np_scores = np.array([1, 2, 3, 4])
print(np_scores)

[1 2 3 4]


Even though you can see that the array printed from Numpy has no commas. It is actually fully functional as a normal python arrays.

In [5]:
print(scores[0])
print(np_scores[0])

1
1


The only thing to note here is that arrays aren't really lists. They provide more functionality than lists.
Python provides an array module for declaring arrays

In [10]:
from array import array


py_scores = array('i', [1, 2, 3, 4])
print(py_scores)

array('i', [1, 2, 3, 4])


The `i` defines the array elements to be of type integer.

Numpy can generate arrays for you.

In [12]:
ones = np.ones(10) # Generate 10 ones

print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


The default type in Numpy is float, that is why you see dots(.) after each 1, which means its 1.0

You can change this by specifying a type

In [13]:
ones = np.ones(10, dtype=int)

print(ones)

[1 1 1 1 1 1 1 1 1 1]


Now you can see the dots(.) are missing

You can also generate zeros

In [14]:
zeros = np.zeros(10, dtype=int)

print(zeros)

[0 0 0 0 0 0 0 0 0 0]


Generate a range of numbers

In [15]:
count_nums = np.arange(1, 10)

print(count_nums)

[1 2 3 4 5 6 7 8 9]


In indexing the starting index is always inclusive and the ending index is always exclusive. In both default python and in Numpy

You can include, stepping.

In [16]:
odd_nums = np.arange(1, 10, 2) # stepping by 2

print(odd_nums)

[1 3 5 7 9]
