# Numpy For Machine Learning

Numpy computations are about 5 to 100 times faster than similar calculations. Because they are implemented in C. For this reason, scipy, pandas, matplotlib and scikit-learn are all built on top of it. Thus knowing Numpy is a neccessity.

In this lesson we will be learning just about enogh numpy to get you started on your study of machine learning or if you want to brush up your knowledge of Numpy.

Python is loosely typed, which means you can always reassign a different type to a variable other than what it was initialy declared with.

For example:

In [ ]:
first = 1
first = "1"
first = True

In C, C++, Java or other compiled languages this will fail.

This characteristic of python is one of the reasons why Python is easier to learn and also the reason why its slower than compiled languages.

Numpy is coded in C. Even though you are not require to declare types, it does type conversion under the hood, converting all elements of your array to the same type.

Lets start off by creating our first array in Numpy.

In [3]:
# Default python array
scores = [1, 2, 3, 4]
print(scores)

[1, 2, 3, 4]


In [4]:
# Numpy array
import numpy as np


np_scores = np.array([1, 2, 3, 4])
print(np_scores)

[1 2 3 4]


Even though you can see that the array printed from Numpy has no commas. It is actually fully functional as a normal python arrays.

In [5]:
print(scores[0])
print(np_scores[0])

1
1


The only thing to note here is that arrays aren't really lists. They provide more functionality than lists.
Python provides an array module for declaring arrays

In [10]:
from array import array


py_scores = array('i', [1, 2, 3, 4])
print(py_scores)

array('i', [1, 2, 3, 4])


The `i` defines the array elements to be of type integer.

Numpy can generate arrays for you.

In [12]:
ones = np.ones(10) # Generate 10 ones

print(ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


The default type in Numpy is float, that is why you see dots(.) after each 1, which means its 1.0

You can change this by specifying a type

In [13]:
ones = np.ones(10, dtype=int)

print(ones)

[1 1 1 1 1 1 1 1 1 1]


Now you can see the dots(.) are missing

You can also generate zeros

In [14]:
zeros = np.zeros(10, dtype=int)

print(zeros)

[0 0 0 0 0 0 0 0 0 0]


Generate a range of numbers

In [15]:
count_nums = np.arange(1, 10)

print(count_nums)

[1 2 3 4 5 6 7 8 9]


In indexing the starting index is always inclusive and the ending index is always exclusive. In both default python and in Numpy

You can include, stepping.

In [16]:
odd_nums = np.arange(1, 10, 2) # stepping by 2

print(odd_nums)

[1 3 5 7 9]


Create an array linearly spaced, between 0 and 1. Number of elements is 10

In [17]:
decimals = np.linspace(0, 1, 10)

print(decimals)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


Create an array of three random numbers

In [19]:
three = np.empty(3, dtype=int)

print(three)

[7340124 7077999 7209081]


Generate a random integer

In [21]:
random_num = np.random.randint(0, 10)

print(random_num)

3


Generate a 2x2 array of random numbers

In [22]:
random_nums = np.random.randint(0, 10, (2,2))

print(random_nums)

[[2 6]
 [6 1]]


You could have also used the size property

In [36]:
random_nums = np.random.randint(0, 10, size=(2, 5))

print(random_nums)

[[2 5 9 4 3]
 [9 9 6 7 4]]


In [37]:
one_dimension_random = np.random.randint(0, 10, size=10)

print(one_dimension_random)

[1 3 2 6 8 9 5 8 9 5]


[Todo]

In [33]:
random_freq = np.random.normal(2, 1, (2, 5))

print(random_freq)


[[4.27797527 2.46585201 1.28659659 1.78570575 1.25716004]
 [1.76036707 0.13369243 1.99671434 4.65063312 2.09755405]]


In [34]:
random = np.random.random((2, 2))

print(random)

[[0.55066805 0.27917928]
 [0.59821943 0.86151309]]


In [35]:
identical = np.eye(3)


print(identical)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Various Types
Data Type | Description

In [ ]:
np.random.seed()

In [ ]:
x = np.random.randint()
x.size()
x.shape()
x.itemsize()
x.nbytes()

In [ ]:
Indexing


In [ ]:
Array slicing

In [ ]:
multidimensional array slicing

In [ ]:
Array no-copy

In [ ]:
copy arrays

In [ ]:
reshaping

In [ ]:
x[np.newaxis, :]

In [ ]:
array broadcasting

In [ ]:
Plotting and images in matplotlib

In [ ]:
Ufuncs

In [ ]:
Array arithmetic

In [ ]:
Table of Arithmetric functions

In [ ]:
out in another array

In [ ]:
reduce

In [ ]:
reduce.accumulate

In [ ]:
sum, min, max

In [ ]:
other functions

In [ ]:
mean, std, median, percentile

In [ ]:
comparison

In [ ]:
randomstate

In [ ]:
counting entries

In [ ]:
axis in sum

In [ ]:
any, all

In [ ]:
array as indeces. Number as indices

In [ ]:
random.choice

In [ ]:
at()

In [ ]:
zero's like bins

In [ ]:
sort, sort axis

In [ ]:
partition, argpartition

In [ ]:
structured arrays
with tuples